In [1]:
import numpy as np
from scipy import linalg, sparse

In [2]:
A = np.matrix(np.random.random((2,2))) # 임의의 2*2 행렬
b = np.random.random((2, 2)) # 2*2의 numpy array를 생성
B = np.asmatrix(b) # 2차원의 배열을 행렬로 변환
C = np.mat(np.random.random((10, 5))) # 임의의 10*5 행렬
D = np.mat([[3, 4],[5, 6]]) # 2차원의 자료를 나타낸 리스트를 행렬로 표현

In [4]:
print(A)

[[0.27763836 0.09803519]
 [0.57689263 0.25586722]]


In [5]:
print(B)

[[0.34727836 0.2677232 ]
 [0.15304803 0.07083985]]


In [6]:
print(C)

[[0.78539039 0.06496752 0.15909012 0.22133321 0.10082181]
 [0.70259761 0.3514021  0.98044455 0.32666257 0.09785622]
 [0.39796225 0.30534467 0.13812191 0.8749169  0.61620216]
 [0.95331429 0.09438137 0.36336528 0.92102543 0.92081628]
 [0.63196487 0.01617935 0.66318828 0.34896708 0.51736926]
 [0.76187074 0.82715664 0.31977392 0.99093441 0.98963602]
 [0.95733897 0.83545844 0.0507548  0.68381576 0.72895532]
 [0.49806038 0.69702272 0.12894031 0.02278899 0.86453239]
 [0.34447373 0.47077906 0.12580416 0.02891603 0.26095571]
 [0.52913184 0.6017668  0.33616509 0.27705632 0.51482639]]


In [7]:
print(D)

[[3 4]
 [5 6]]


In [10]:
A.I # A의 역행렬

matrix([[ 17.66699819,  -6.76908714],
        [-39.83300787,  19.17024175]])

In [11]:
linalg.det(A) #A의 행렬식 det(A)

0.014482778384430552

In [13]:
A.T # A의 전치행렬

matrix([[0.27763836, 0.57689263],
        [0.09803519, 0.25586722]])

In [14]:
np.add(A,D) # A와 D의 합

matrix([[3.27763836, 4.09803519],
        [5.57689263, 6.25586722]])

In [15]:
np.subtract(A, D) # A와 D의 차

matrix([[-2.72236164, -3.90196481],
        [-4.42310737, -5.74413278]])

In [16]:
np.divide(A, D) # A 나누기 D

matrix([[0.09254612, 0.0245088 ],
        [0.11537853, 0.04264454]])