In [6]:
import numpy as np
a = np.mat(
[
    [1, 0],
    [-3, 2],
    [8, 4]
])

b = np.mat(
[
    [4, 4],
    [1, -5],
    [7, 9]
])

c = np.mat(
[
    [5, 1, -2],
    [3, 1, 5],
    [4, -7, 8]
])

d = np.mat(
[
    [1, 0, 6],
    [3, -1, 4],
    [0, 5, -3]
])

In [20]:
import numpy as np
a = np.mat(
[
    [-5, 0],
    [1, 2]
])

b = np.mat(
[
    [0, 4, 2],
    [7, 1, 5],
    [-2, -7, 9]
])

c = np.mat(
[
    [6, 3],
    [5, -4],
    [-2, 9]
])

d = np.mat(
[
    [-1, 2],
    [5, -2],
    [0, 3]
])

In [35]:
-9*d

matrix([[  9, -18],
        [-45,  18],
        [  0, -27]])

In [3]:
import numpy as np
a = np.mat(
[
    [1, 1],
    [1, 1]
])

b = np.mat(
[
    [5, 5],
    [1, 0]
])


c = np.mat(
[
    [-4, 3],
    [5, 0],
    [-1, 8]
])

d = np.mat(
[
    [0, 6, -4],
    [6, 2, 7],
    [-4, 7, 5]
])

e = np.mat(
[
    [1, -7, 4],
    [6, 5, 0],
    [3, -1, 5]
])

f = np.mat(
[
    [-8, 4, 1, -5],
    [-2, 0, 0, 0],
    [7, 3, -5, 9]
])

g = np.mat(
[
    [1, 5, -1, -5],
    [0, 8, 4, -3],
    [2, -6, 7, 7],
    [9, -2, 5, -9]
])
h = np.mat(
[
    [4, -7, 3, 9],
    [-7, 5, 8, -2],
    [3, 8, -2, 0],
    [9, -2, 0, -9]
])

In [7]:
print("a:", a.T)
print("b:", b.T)
print("c:", c.T)
print("d:", d.T)
print("e:", e.T)
print("f:", f.T)
print("g:", g.T)
print("h:", h.T)

a: [[1 1]
 [1 1]]
b: [[5 1]
 [5 0]]
c: [[-4  5 -1]
 [ 3  0  8]]
d: [[ 0  6 -4]
 [ 6  2  7]
 [-4  7  5]]
e: [[ 1  6  3]
 [-7  5 -1]
 [ 4  0  5]]
f: [[-8 -2  7]
 [ 4  0  3]
 [ 1  0 -5]
 [-5  0  9]]
g: [[ 1  0  2  9]
 [ 5  8 -6 -2]
 [-1  4  7  5]
 [-5 -3  7 -9]]
h: [[ 4 -7  3  9]
 [-7  5  8 -2]
 [ 3  8 -2  0]
 [ 9 -2  0 -9]]


In [12]:
import numpy as np
a = np.mat(
[
    [1, 3],
    [5, 1],
    [8, 0]
])

b = np.mat(
[
    [7, 1],
    [4, 5]
])

c = np.mat(
[
    [4, 5, 3],
    [8, 0, 1],
    [2, 7, 2]
])

d = np.mat(
[
    [0, 1, 2],
    [0, 3, 4]
])

In [30]:
a*b

matrix([[19, 16],
        [39, 10],
        [56,  8]])

In [13]:
c1 = np.mat(
[
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])


In [15]:
c2 = np.mat(
[
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])


In [18]:
c1+c == c+c1

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])

In [5]:
import numpy as np
import numpy.linalg as LA
np.random.seed(0)
a = np.mat(
[
    [8, 3],
    [-2, -2]
])

b = np.mat(
[
    [3, 4],
    [6, 8]
])

c = np.mat(
[
    [6, -1],
    [2, 3]
])

d = np.mat(
[
    [3, -5, 1],
    [3, 2, -1],
    [-1, -1, 1]
])

In [34]:
LA.det(a)

-9.999999999999998

In [35]:
LA.det(b)

0.0

In [36]:
LA.det(c)

20.000000000000007

In [8]:

inv_d = LA.inv(d)

In [ ]:
x = d * b

print(x)
print(np.shape(x))

In [11]:
import numpy as np
import numpy.linalg as LA
A = np.mat(
[
    [3, -5, 1],
    [3, 2, -1],
    [-1, -1, 1]
])
B = np.mat(
[
    [-3],
    [0],
    [1]
])

In [39]:
import numpy as np
import numpy.linalg as LA
A = np.mat(
[
    [5, -1, 1],
    [1, 1, 3],
    [-2, 2, 4]
])
B = np.mat(
[
    [-6],
    [0],
    [2]
])

In [61]:
import numpy as np
import numpy.linalg as LA
A = np.mat(
[
    [ 2, 3],
    [2, 6, 8],
    [1, 5, 6]
])
B = np.mat(
[
    [7],
    [10],
    [1]
])

C:\Users\grupi\anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


In [58]:
A_inv = LA.inv(A)

print(A_inv)

UFuncTypeError: Cannot cast ufunc 'inv' input from dtype('O') to dtype('float64') with casting rule 'same_kind'

In [60]:
x = A_inv * b
print(x)

[[ 2.5]
 [ 4.5]
 [-4. ]]


In [49]:
3*0.166+2*(-2.833)+2.166

-3.0020000000000002

In [38]:
round(1.66533454e-16,18)

1.67e-16